pipeline {

    agent any
 stages {
  stage('Docker Build and Tag') {
           steps {
              
                sh 'docker build -t nginxtest:latest .' 
                sh 'docker tag nginxtest PR345876/nginxtest:latest'
                sh 'docker tag nginxtest PR345876/nginxtest:$BUILD_NUMBER'
               
          }
        }
     
  stage('Publish image to Docker Hub') {
          
            steps {
        withDockerRegistry([ credentialsId: "Dockerhub", url: "" ]) {
          sh  'docker push PR345876/nginxtest:latest'
          sh  'docker push PR345876/nginxtest:$BUILD_NUMBER' 
        }
                  
          }
        }
     
      stage('Run Docker container on Jenkins Agent') {
             
            steps {
                sh "docker run -d -p 4030:80 PR345876/nginxtest"
 
            }
        }
 
    }
}

